package id.ac.poliban.mi.firah.listviewclubligaenglish;

import java.util.ArrayList;
import java.util.List;

public class TimData {

    static List<Tim> getTimList(){
        List<Tim> data = new ArrayList<>();
        {
            data.add(new Tim("https://upload.wikimedia.org/wikipedia/id/thumb/7/7a/Manchester_United_FC_crest.svg/330px-Manchester_United_FC_crest.svg.png","Manchester United F.C.","Manchester United Football Club adalah sebuah klub sepak bola profesional Inggris yang berbasis di Old Trafford, Manchester Raya, yang bermain di Liga Inggris. Didirikan sebagai Newton Heath LYR Football Club pada tahun 1878, klub ini berganti nama menjadi Manchester United pada 1902 dan pindah ke Old Trafford pada tahun 1910."));
            data.add(new Tim("https://upload.wikimedia.org/wikipedia/id/thumb/0/0f/Blackburn_Rovers.svg/300px-Blackburn_Rovers.svg.png","Blackburn Rovers F.C.","Blackburn Rovers Football Club adalah sebuah tim sepak bola Inggris yang saat ini bermain di Liga Championship Inggris. Bermarkas di Blackburn, Inggris. Didirikan tahun 1875. dan pernah menjuarai liga utama inggris sebanyak 3 kali."));
            data.add(new Tim("https://upload.wikimedia.org/wikipedia/id/thumb/5/53/Arsenal_FC.svg/270px-Arsenal_FC.svg.png","Arsenal F.C.","Arsenal Football Club (dikenal pula sebagai Arsenal atau The Gunners) adalah klub sepak bola profesional Inggris yang berbasis di daerah Holloway, London. didirikan pada 1886 dengan nama Dial Square. Klub ini bermain di Liga Utama Inggris yang termasuk salah satu klub tersukses di sepak bola Inggris, yang telah memenangkan 13 gelar kasta utama Liga Inggris (10 pada era Divisi Pertama dan 3 pada era Premier League) dan 13 gelar di Piala FA (Gelar paling banyak). Arsenal memegang rekor untuk periode terpanjang berada di kasta puncak Liga Inggris tanpa pernah terdegradasi sejak musim 1919 dan menjadi tim pada peringkat pertama dalam klasemen Liga Inggris sepanjang abad ke-20.[4] Arsenal menjadi tim kedua di Inggris yang menyelesaikan semusim liga tanpa kalah (musim 2003–04) dan tim pertama yang melakukannya pada era di mana satu musim berlangsung 38 pertandingan."));
            data.add(new Tim("https://upload.wikimedia.org/wikipedia/id/thumb/c/cc/Chelsea_FC.svg/300px-Chelsea_FC.svg.png","Chelsea F.C.","Chelsea Football Club /ˈtʃɛlsiː/ adalah sebuah klub sepak bola Inggris yang bermarkas di Fulham, London. Chelsea didirikan pada tahun 1905 dan kini berkompetisi di Liga Utama Inggris.\n" +
                    "\n" +
                    "Kesuksesan pertama Chelsea diraih saat meraih gelar juara liga pada tahun 1955. Beberapa gelar dari berbagai kompetisi juga berhasil diraih pada dekade 1960an, 1970an, 1990an, dan 2000an. Sepanjang sejarah penampilan dalam dunia sepak bola di Inggris dan Eropa, Chelsea telah meraih enam gelar juara Liga Utama Inggris, delapan Piala FA, lima Piala Liga, dua Liga Eropa UEFA, dua Piala Winners UEFA, satu Liga Champions UEFA, dan satu Piala Super UEFA.[3] Dalam dua dekade terakhir merupakan periode terbaik kesuksesan Chelsea dengan meraih lebih dari 30 gelar sejak tahun 1997, termasuk untuk pertama kali meraih gelar ganda, Liga Utama Inggris dan Piala FA pada tahun 2010 serta gelar juara Liga Champions UEFA pada tahun 2012 dan Liga Eropa UEFA pada 2013 dan 2019.[4][5] "));
            data.add(new Tim("https://upload.wikimedia.org/wikipedia/id/thumb/e/eb/Manchester_City_FC_badge.svg/300px-Manchester_City_FC_badge.svg.png","Manchester City F.C","Manchester City Football Club (dikenal pula sebagai Man City atau The Citizens) adalah sebuah klub sepak bola profesional dari Inggris yang bermain di Liga Premier Inggris. Klub ini merupakaan klub sekota dengan Manchester United dan bermarkas di Stadion Etihad, Manchester."));
            data.add(new Tim("https://upload.wikimedia.org/wikipedia/id/thumb/0/0f/Blackburn_Rovers.svg/300px-Blackburn_Rovers.svg.png","Blackburn Rovers F.C.","Blackburn Rovers Football Club adalah sebuah tim sepak bola Inggris yang saat ini bermain di Liga Championship Inggris. Bermarkas di Blackburn, Inggris. Didirikan tahun 1875. dan pernah menjuarai liga utama inggris sebanyak 3 kali."));
            data.add(new Tim("https://upload.wikimedia.org/wikipedia/id/thumb/f/f9/Aston_Villa_FC_crest_%282016%29.svg/225px-Aston_Villa_FC_crest_%282016%29.svg.png","Aston Villa F.C.","Aston Villa Football Club (/ˈæstən ˈvɪllə/; juga dikenal sebagai Villa, The Villa, The Villans dan The Lions)[5] adalah klub sepak bola profesional yang bermarkas di Villa Park, Birmingham, Inggris. Klub ini bermain di Liga Utama Inggris dan merupakan salah satu klub pendiri Liga Sepak Bola (Football League) pada tahun 1888 serta Liga Utama pada tahun 1992. Aston Villa merupakan salah satu klub tertua dan tersukses Inggris."));
            data.add(new Tim("https://upload.wikimedia.org/wikipedia/id/thumb/8/8c/Norwich_City.svg/225px-Norwich_City.svg.png","Norwich City F.C.","Norwich City Football Club adalah sebuah klub sepak bola Inggris yang didirikan pada tahun 1902. Bermarkas di Norwich, Norfolk. Norwich pada musim 2006-07 bermain di Liga Championship Inggris. Klub ini memainkan pertandingan kandangnya di Stadion Carrow Road yang berkapasitas 26.164 penonton. Seragam mereka berwarna kuning-hijau, sehingga mereka dijuluki Canaries (Kenari)."));
            data.add(new Tim("https://upload.wikimedia.org/wikipedia/id/thumb/0/0c/Liverpool_FC.svg/270px-Liverpool_FC.svg.png","Liverpool F.C.","Liverpool Football Club /ˈlɪvərpuːl/ (dikenal pula sebagai Liverpool atau The Reds) adalah sebuah klub sepak bola asal Inggris yang berbasis di Kota Liverpool. Saat ini Liverpool adalah peserta Liga Utama Inggris. Liverpool juga merupakan juara bertahan Liga Champions UEFA musim 2018-2019\n" +
                    "\n" +
                    "Liverpool telah memenangkan 6 trofi Liga Champions UEFA (dulu Piala Champions) dan merupakan klub dengan pemegang gelar juara Liga Champions UEFA terbanyak di Inggris dan ketiga di Eropa setelah Real Madrid dan AC Milan[3]. Selain itu Liverpool juga pemegang 3 gelar juara Liga Eropa UEFA[4] dan 4 gelar Piala Super UEFA[5]."));
            data.add(new Tim("https://upload.wikimedia.org/wikipedia/id/thumb/5/56/Newcastle_United_Logo.svg/300px-Newcastle_United_Logo.svg.png", "Newcastle United F.C.", "Newcastle United Football Club adalah klub sepak bola profesional Inggris yang berbasis di Newcastle upon Tyne, dan bermain di Liga Utama Inggris, kompetisi tingkat teratas dalam sepak bola Inggris. Newcastle United didirikan pada tahun 1892 sebagai hasil penggabungan Newcastle East End dan Newcastle West End, dan bermain di kandangnya saat ini, St James' Park, sejak saat itu. Stadion tersebut dikembangkan menjadi stadion all-seater pada pertengahan 1990-an dan memiliki kapasitas 52.354."));
        }
        return data;
    }
}
